a=int(input('整数値a：'))
b=int(input('整数値b：'))
print('a < b :',a < b)
print('a <= b :',a <= b)
print('a > b :',a > b)
print('a >= b :',a >= b)
print('a == b :',a == b)
print('a != b :',a != b)
print('False :',False)
print('True :',True)
print('True  + 5:',True + 5)
